### ISSUE TITLE
来讨论设计方案

### ISSUE THREAD

**Issue by ylc395** [UESTC-FEDOG/UESTC-FEDOG#1]
顺便学习如何使用Issues功能。
我们可以在一个repository里提出一个Issue并在这个Issue下进行讨论。
讨论完毕后可以close这个Issue

Pull request（俗称PR）本质上也是Issue的一种

Issues内容编辑界面支持使用Markdown语法，可以查看编辑界面下方的[Styling with Markdown is supported](https://guides.github.com/features/mastering-markdown/)
- [ ] - 学会Issue功能
- [ ] - 完成设计稿

**Comment by kkmikako** [comment]
- 主题页面
  
  ![如图](http://www.yingzi007.com/wp-content/uploads/2014/09/14082901.jpg)

如图撑满整个页面，头像就是我们三个人自己上传自己喜欢的图片，team就写UESTC_FEDOG，每个人的头像鼠标放上去都会产生翻转效果,背景颜色，具体参数再议
- 个人页面
  现在想到了两种方式，一种是[fullpages](http://zhangwenli.com/cv/cn.html)，使用张雯丽的这种fullpages，往下滑动页面出现每个人的简介，写好响应式，另外一种是点击每个人的头像和名字跳转到每个人的个人简介页面（在第一种里面我们由前端路由同样可以实现跳转，后一种是单独的页面，独立性更强，可以每个人自己个人设计，fullpages这种我们就风格统一）
  
  上面是想到的大体实现思路，希望大家能提出更好的想法，集思广益

**Comment by ylc395** [comment]
我敢打赌，100个人里有90个人爱用fullpage。
我们可以更简单一点

**Comment by ylc395** [comment]
等等，我突然想问，团队页面是必做题么？

**Comment by yinyanli** [comment]
感觉是，点击图像之后，背景虚化，出现个人简介，页面会不会简单一点

**Comment by ylc395** [comment]
知乎上看到的一个，挺漂亮的：http://www.apollozz.com/

**Comment by kkmikako** [comment]
团队页面是热身题，算是半个必做题，知乎上那个页面确实挺漂亮的，我们在个人页面的时候可以这么做，所以主页面大体样式确定下来是上图的那样吗

**Comment by ylc395** [comment]
全在一页里还是做多页？

**Comment by kkmikako** [comment]
多页指的是跳转新页面，还是fullpage这种多页，全在一页指的是知乎那个页面全部由jq控制css在一个页面里面复现那样的吗

**Comment by ylc395** [comment]
> 多页指的是跳转新页面

指跳转

我觉得就全在一页里写完就完了。各开一个新页面没那么多东西可写。还有抵制fullpage，人人有责

**Comment by kkmikako** [comment]
同意
不过抵制fullpage是什么鬼
效果，可以按照yinyanli说的，点击个人头像以后，背景虚化呈现每个人的简介
具体简介出现可以按照知乎那个简历页面那样一行一行延迟出现，不过写法应该可以聪明点，全用jQeury那样控制css感觉好蠢

**Comment by ylc395** [comment]
> 点击个人头像以后，背景虚化呈现每个人的简介

就这样吧。我觉得也不用一行行出现了，动画在大部分情况下都令人抓狂。知名大站没几个是有动画效果的

**Comment by kkmikako** [comment]
ok，等yinyanli确认下，我们就把方案定下来

**Comment by yinyanli** [comment]
非常抱歉，今天忘了登这个，现在才看到，所以现在的方案就是背景虚化出现个人简介，然后个人简介又按知乎那个么

**Comment by ylc395** [comment]
@yinyanli 不是的，请忘记知乎那个。自我介绍非常简单的，就两三行，没有任何特技

**Comment by yinyanli** [comment]
可以呀，要不然自我介绍都不知道写些啥

**Comment by ylc395** [comment]
@kkmikako OK，那么设计方案就这样定了，简单一点就好...

还有这个团队页面的截止日期是什么？

最后，我新开了一个Issue用来讨论部署的方式。请在那儿继续讨论。如果没有与设计方案有关的其他讨论，可以将这个Issue关闭

**Comment by kkmikako** [comment]
ok,设计方案就这样，截止时间是3.14

**Comment by ylc395** [comment]
那么这个Issue就关闭了。请移至下一个Issue讨论下一个话题。

@UESTC-FEDOG/fedogs
