### ISSUE TITLE
页面部署的讨论

### ISSUE THREAD

**Issue by ylc395** [UESTC-FEDOG/UESTC-FEDOG#2]
在这里讨论页面如何部署在线上。

**Comment by yinyanli** [comment]
页面上的图像就用脸萌自己弄一个吧，好萌啊

**Comment by ylc395** [comment]
> 页面上的图像就用脸萌自己弄一个吧，好萌啊

请勿在这个Issue下讨论与主题无关的问题。可以回#1讨论

**Comment by kkmikako** [comment]
部署方式我目前想到了三种，1，直接部署在github.io上，；2，我有个海外vps，把uestc-fedog.xxx的域名搞过来，部署上去；3，页面部署在cyl的个人博客上，添加个路由（不知道cyl介不介意）

**Comment by ylc395** [comment]
> 直接部署在github.io

其实我倾向这个方案。以后有更多页面要部署的话也方便。

不过我需要一点时间学习。你掌握了如何操作github.io了么？

**Comment by kkmikako** [comment]
四个月前部署过一次hexo个人博客，现在基本忘光了。。。。不过是基于nodejs的，应该不是特别难，大家一起学习

**Comment by ylc395** [comment]
官方文档在https://help.github.com/categories/github-pages-basics/

这个Issue会保留至部署成功

**Comment by ylc395** [comment]
我看了下Guide，超简单。前提是你已经学会了Git和Github的基本使用。简单地说，需要将team-page项目更名为与organization同名，然后将页面推送到UESTC-FEDOG项目下的master分支下即可通过`http://UESTC-FEDOG.github.io/`访问到了
- [x] 将项目更名

请大家最近几天熟悉一下Git和Github，有问题的话可以通过QQ讨论群联系。页面的实际制作最多不超过两天。

@UESTC-FEDOG/fedogs
