### ISSUE TITLE
team-page开发

### ISSUE THREAD

**Issue by kkmikako** [UESTC-FEDOG/UESTC-FEDOG#3]
1. 关于页面制作计划的具体时间没有做出规划（第一阶段开发完成截止时间，第二阶段codereview完成截止时间，第三阶段部署完成截止时间）
2. 设计，初次开发，迭代，codereview，部署，分工不明确
3. 团队交流过于离散，通过qq交流效率低下，希望接下来在ife中大家多多使用GitHub的issue来进行正式交流，有关于开发方面的问题在issue中正式提出
4. 个人能力问题，目前我个人默认自己css能力为零分，没能写出第一个demo
5. 现在有时间对team-page页面的开发部署做拯救吗？

ps：请大家提出下意见，关于这次模拟合作开发的问题

**Comment by ylc395** [comment]
我觉得把我的分支的半成品上个色就可以完成团队页面的任务了…页面结构、动画和响应式，只要那种程度就足够了。我看了一些团队的团队页面，比我的半成品还简单的也不少

**Comment by kkmikako** [comment]
我觉得可行，我想了下，作为一个产品还有几点想法：
- 个人图片还需要自己上传
- 个人简介需要自己写（每个人个性化，还是统一样式？）
- 最后部署的截止时间

这几点理清楚就好

**Comment by ylc395** [comment]
感觉今晚就能搞定吧…你把大家的收集下放入public文件夹就好，个人简介每人两行

**Comment by ylc395** [comment]
对了，yyl也写了相当复杂的页面。她如果完工的话看下她的吧，顺便你帮她点评一下代码
